"""cart item again

Revision ID: 04d0859a0ac6
Revises: 967435abcedb
Create Date: 2025-12-18 20:23:07.307078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d0859a0ac6'
down_revision: Union[str, None] = '967435abcedb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop and recreate cart_items table with UUID id
    op.drop_table('cart_items')
    op.create_table('cart_items',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('cart_id', sa.UUID(), nullable=False),
        sa.Column('product_id', sa.UUID(), nullable=False),
        sa.Column('container', sa.String(), nullable=True),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=True)
    op.add_column('order_items', sa.Column('container', sa.String(), nullable=True))
    op.drop_column('order_items', 'color')
    op.drop_column('order_items', 'size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('order_items', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('order_items', 'container')
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.alter_column('cart_items', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
