"""shipping address change

Revision ID: 48c8aa41659b
Revises: 203013a708b1
Create Date: 2026-01-08 15:31:28.971156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c8aa41659b'
down_revision: Union[str, None] = '203013a708b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipping_addresses', sa.Column('address', sa.String(), nullable=True))
    op.add_column('shipping_addresses', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('shipping_addresses', sa.Column('apartment', sa.String(), nullable=True))
    op.add_column('shipping_addresses', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipping_addresses', 'note')
    op.drop_column('shipping_addresses', 'apartment')
    op.drop_column('shipping_addresses', 'phone')
    op.drop_column('shipping_addresses', 'address')
    # ### end Alembic commands ###
