"""cart item

Revision ID: 967435abcedb
Revises: 3fe5ffb71a42
Create Date: 2025-12-18 20:15:48.359711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '967435abcedb'
down_revision: Union[str, None] = '3fe5ffb71a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('container', sa.String(), nullable=True))
    op.drop_column('cart_items', 'color')
    op.drop_column('cart_items', 'size')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('size', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cart_items', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('cart_items', 'container')
    # ### end Alembic commands ###
