"""order schema change

Revision ID: c08756b558b6
Revises: 8799ba4c0373
Create Date: 2025-12-19 14:22:05.253565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c08756b558b6'
down_revision: Union[str, None] = '8799ba4c0373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('name', sa.String(), nullable=True))
    op.add_column('order_items', sa.Column('image', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('internal_notes', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'internal_notes')
    op.drop_column('order_items', 'image')
    op.drop_column('order_items', 'name')
    # ### end Alembic commands ###
