"""order schema

Revision ID: f08c495e73c2
Revises: ac2c08c53b9a
Create Date: 2025-12-19 11:07:00.061083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f08c495e73c2'
down_revision: Union[str, None] = 'ac2c08c53b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('size', sa.String(), nullable=True))
    op.add_column('order_items', sa.Column('color', sa.String(), nullable=True))
    op.drop_constraint('order_items_order_id_key', 'order_items', type_='unique')
    op.drop_constraint('order_items_product_id_key', 'order_items', type_='unique')
    op.drop_column('order_items', 'container')
    op.add_column('orders', sa.Column('city', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('area', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('address', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('phoneNumber', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('apartment', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payOnDelivery', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('paid', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('mpesaCode', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('additionalNote', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('shipping_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipping_method')
    op.drop_column('orders', 'additionalNote')
    op.drop_column('orders', 'mpesaCode')
    op.drop_column('orders', 'paid')
    op.drop_column('orders', 'payOnDelivery')
    op.drop_column('orders', 'apartment')
    op.drop_column('orders', 'phoneNumber')
    op.drop_column('orders', 'address')
    op.drop_column('orders', 'area')
    op.drop_column('orders', 'city')
    op.add_column('order_items', sa.Column('container', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('order_items_product_id_key', 'order_items', ['product_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint('order_items_order_id_key', 'order_items', ['order_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('order_items', 'color')
    op.drop_column('order_items', 'size')
    # ### end Alembic commands ###
